version: '3.8'

services:
  ollama:
    build: 
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s


  interview-app:
    build: .
    container_name: interview-app
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8501:8501"
